# This file was generated by ‘nixos-generate-config’ and may be overwritten by future invocations.
# After generating this file I copied it to macbookair2013/ virtualbox2015/ directories.
{ ... }:

{

}
