# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
      <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/24103c2c-a659-4273-b139-69750693a131";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/31220780-f07d-4604-959b-4fe1732b45b5";
      fsType = "ext4";
    };

  # Don't list the swap device explictly for now due to a bug with systemctl, see nipkgs #5202, #5193, 5258
  # swapDevices =
  #   [ # { label = "swap"; }
  #     { device = "/dev/disk/by-uuid/e990939c-a825-497e-aec6-facc74823e90"; }
  #   ];

  nix.maxJobs = 8;
  virtualisation.virtualbox.guest.enable = true;
}
